### ISSUE TITLE
`logout()` doesn't resolve

### ISSUE THREAD

**Issue by leebenson** [feathersjs/feathers-authentication-client#10]
`app.logout()` returns a promise that never resolves.

**Comment by bertho-zero** [comment]
I have the same issue, for me it is only after a refresh of the page, it's the callback of the `emit` which is never called.

**Comment by ekryski** [comment]
Hmm. Weird. We have tests around this and we log out all the time. Are you using sockets? Seeing any errors?

**Comment by leebenson** [comment]
I was using Primus, yup.

**Comment by ekryski** [comment]
@bertho-zero were you also using Primus?

**Comment by bertho-zero** [comment]
No, I use socket.io

**Comment by ekryski** [comment]
So @leebenson @bertho-zero when you call `logout` is the `feathers-jwt` key still in localstorage?

**Comment by bertho-zero** [comment]
Yes, but after a refresh of the page the server does not receive the logout socket.

**Comment by marshallswain** [comment]
The problem is that the callback here doesn't get called because there's not a response from the server:
https://github.com/feathersjs/feathers-authentication-client/blob/master/src/passport.js#L167,
So neither `reject` nor `resolve` gets hit.

**Comment by bertho-zero** [comment]
For me it works since I think to reconnect the socket after refresh (https://github.com/feathersjs/feathers-authentication/issues/372)

**Comment by xtechnet** [comment]
i have the same problem,`logout ` does not  always  worked out ,by some times
