### ISSUE TITLE
Missing auth token when used with feathers-rest in comparison to feathers-socketio

### ISSUE THREAD

**Issue by ianmaroney** [feathersjs/feathers-authentication-client#16]
### Steps to reproduce

Using a working server-side authentication setup (in my case Google via OAuth2), upon redirect to a generic `/success.html` page after authentication; Test code feathers-socketio and feathers-rest for client-side authentication.

Toggle between commenting out and uncommenting the lines containing `.configure(rest('http://localhost:3030').superagent(superagent))` and `.configure(socketio(socket))`.

```// SOCKET REQUIREMENTS
const socketio = require('feathers-socketio/client');
const io = require('socket.io-client');

// REST REQUIREMENTS
const rest = require('feathers-rest/client');
const superagent = require('superagent');

// FEATHERS REQUIREMENTS
const feathers = require('feathers/client');
const hooks = require('feathers-hooks');
const localStorage = require('localstorage-memory');
const auth = require('feathers-authentication-client');

const socket = io('http://localhost:3030');
const host = 'http://localhost:3030';
const client = feathers();

client.configure(hooks())
  // .configure(rest('http://localhost:3030').superagent(superagent)) // When attempting client.get('user') below, this leads to a 401 and the req on the server reports being empty
  .configure(socketio(socket)) // When attempting client.get('user') below, this returns a user object as expected
  .configure(auth({ storage: localStorage }));

client.authenticate()
.then(response => {
  console.log('Authenticated!', response);
  return client.passport.verifyJWT(response.accessToken);
})
.then(payload => {
  console.log('JWT Payload', payload);
  return client.service('users').get(payload.userId);
})
.then(user => {
  client.set('user', user);
  console.log('User', client.get('user')); // <-- HERE
})
.catch(function (error) {
  console.error('Error authenticating!', error);
});
```

Running this would result in a 401 for the `rest` method and success for the `socket.io` method. Logging the `req` in `{PROJECT}/node_modules/passport-jwt/lib/strategy.js` `authenticate()` confirms that the `socket.io` method is working while the `rest` method appears to drop its information at some point.

### Expected behavior
The two methods should behave the same.

### Actual behavior
The rest version seems to lose its authentication.

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):

    "body-parser": "^1.15.2",
    "compression": "^1.6.2",
    "cors": "^2.8.1",
    "feathers": "^2.0.3",
    "feathers-authentication": "^1.0.2",
    "feathers-authentication-client": "0.1.6",
    "feathers-authentication-jwt": "^0.3.0",
    "feathers-authentication-oauth2": "^0.2.3",
    "feathers-configuration": "^0.3.3",
    "feathers-errors": "^2.5.0",
    "feathers-hooks": "^1.7.0",
    "feathers-hooks-common": "^2.0.2",
    "feathers-nedb": "^2.6.0",
    "feathers-permissions": "0.1.1",
    "feathers-rest": "^1.5.2",
    "feathers-socketio": "^1.4.2",
    "nedb": "^1.8.0",
    "passport": "^0.3.2",
    "passport-asana": "0.0.1",
    "passport-google-oauth20": "^1.0.0",
    "passport-google-token": "^0.1.2",
    "serve-favicon": "^2.3.2",
    "winston": "^2.3.0"

**NodeJS version**:
v7.2.0

**Operating System**:
macOS Sierra 10.12.2

**Browser Version**:
Chrome 55.0.2883.95

**Comment by ekryski** [comment]
@ianmaroney you can't use both socketio/primus and rest in the same client. The justification is that if you already have sockets, why not just use them? The code in your app that you write is the exact same regardless of the transport used.

If you want to have more than one transport you need to create multiple client instances.

We have an issue in the main feathers repo to throw a proper error when both are registered on the client. Thanks for creating such a great issue! It was really easy to see what the problem is.
