### ISSUE TITLE
[Feature request] Signup via socket

### ISSUE THREAD

**Issue by ForsakenHarmony** [feathersjs/feathers-authentication-client#17]
Would be super nice if you could also sign up via socket.io and not just log in

if this already works I'm sorry, I couldn't find anything

**Comment by daffl** [comment]
You can. `users` is just a service, if you have a socket connection established just run

```js
app.service('users').create({ email, password });
```

**Comment by ForsakenHarmony** [comment]
Oh, nice thanks
