### ISSUE TITLE
Socket client should automatically auth on reconnect

### ISSUE THREAD

**Issue by marshallswain** [feathersjs/feathers-authentication-client#2]
@marshallswain commented on [Wed Oct 12 2016](https://github.com/feathersjs/feathers-authentication/issues/310)

I'm in the process of making a new version of can-connect-feathers that uses the real feathers-client.  This is something that probably ought to be in the feathers-auth client.

``` js
  /**
   * When the socket gets disconnected, this makes sure that it re-authenticates
   * upon reconnection. It simply calls `authenticateSocket` and persists
   * the token.
   */
  handleSocketReconnects(data){
    // Make sure the socket re-authenticates if it gets disconnected.
    this.io.on('reconnect', () => {
      this.authenticateSocket(data)
        .then(data => this.persistToken(data))
        .then(data => this.makeSSRCookie(data));
    });
  }
```

**Comment by marshallswain** [comment]
This fixes https://github.com/feathersjs/feathers-authentication/issues/272

**Comment by ekryski** [comment]
I thought this was complete but there is a bug so I'm not going to close this just yet. I'm not testing a server shutdown only emitting a `reconnect` event from the server, which works but that doesn't accurately reflect a real world disconnect.

**Comment by ekryski** [comment]
Closed by #9

**Comment by efgonz** [comment]
@marshallswain @ekryski After #9 feathers deals with reconnection or it needs any configuration? I'm having a lot of problems with reconnection.

**Comment by marshallswain** [comment]
@efgonz can you describe in more detail the problems you are seeing?

**Comment by efgonz** [comment]
Thanks for answering @marshallswain, I have looked around and your support is awfully good here. Describing my issue: I have gotten into feathers js in a new team, so I'm new with it , they have "feathers-authentication": "0.7.12", and they decided that won't migrate to v.1 where I can see that to implement re-authentication after server goes down or the client loses connectivity is supported and simple with feathers-authentication-client, but for v.0.7, what are my options? Thanks in advanced.

**Comment by marshallswain** [comment]
@efgonz you'll need to `setTimeout` at login to call `app.authenticate` again with the JWT.

**Comment by efgonz** [comment]
@marshallswain I already based on feathers-authentication-client and works perfectly , thank you for the support.
