### ISSUE TITLE
Re-authenticating fails when passing options

### ISSUE THREAD

**Issue by juanchoc** [feathersjs/feathers-authentication-client#22]
### Steps to reproduce

1- Authenticate using the `local` strategy.

```
app.authenticate({
      strategy: 'local',
      'email': email,
      'password': password
    })
```

2- Navigate to another page.

3- The jwt token is obtained successfully and is available when calling `app.passport.getJWT()`, and verifies successfully when calling `app.passport.verifyJWT(token)`.

4- Try to re-authenticate, passing `jwt` as the strategy.

```
app.authenticate({
      strategy: 'jwt'
    });
```

### Expected behavior

The re-authentication should succeed.

### Actual behavior

Re-authentication fails.
Calling authenticate() without any options works correctly.

### System configuration

**Module versions**: feathers-authentication-client 0.1.6

**NodeJS version**: 6.9.4

**Comment by marshallswain** [comment]
If you're going to pass options, you need to pass all of the ones required for the strategy you're using.  The `accessToken` is missing from the options you're passing.  This is behavior that was also available in the original auth, and we've kept it around.

**Comment by daffl** [comment]
If you don't pass anything (like `app.authenticate()`) it will try to authenticate with the token from storage though right?

**Comment by daffl** [comment]
As pointed out, you either call `app.authenticate()` with no options which will use the token from storage or the full options with

```
app.authenticate({
  strategy: 'jwt',
  token: 'mytoken'
});
```

**Comment by alexisohayon** [comment]
I have the same problem, I try to make an impersonate strategy and I want to be able to authenticate by "jwt" but never working. It seems that the call `feathers.authenticate({strategy: 'jwt', token: accessToken})` is never taking into account the token, using therefore the one from storage.
If I only do a verification of the token, it works and returns the userId of the impersonated user, but with authenticate, it only returns my own accessToken... Any idea?

**Comment by alexisohayon** [comment]
@juanchoc did you manage to make it work? @daffl have you ever been is a situation like this one?
