### ISSUE TITLE
Browser Version

### ISSUE THREAD

**Issue by guiguan** [feathersjs/feathers-authentication-client#24]
Hi, can you provide a browser version for this module? 

I have tried to build one using webpack, but I got following error:

![screen shot 2017-01-23 at 6 44 31 pm](https://cloud.githubusercontent.com/assets/940189/22195421/04a098de-e19c-11e6-818e-5f1b84a61237.png)

Here is my webpack config:
```js
const path = require('path');

module.exports = {
  entry: './node_modules/feathers-authentication-client',
  target: 'node',
  output: {
    path: path.join(__dirname, '/dist'),
    filename: 'bundle.js'
  },
  devtool: 'sourcemap'
};
```

**Comment by marshallswain** [comment]
By browser version, do you want a version that will load in a script tag?

**Comment by guiguan** [comment]
Yes, or a version that could be packed by webpack :P

**Comment by daffl** [comment]
I don't see a reason why the packaged version wouldn't be compatible with Webpack. @marshallswain Could it be a configuration issue?

**Comment by marshallswain** [comment]
@guiguan instead of trying to pack the compiled version, clone the repo and pack the src.

**Comment by daffl** [comment]
The transpiled version in `lib` that comes with the npm package should be usable with any module loader already. The old `feathers-authentication/client` definitely was, is that not the case anymore?
