### ISSUE TITLE
Uncaught TypeError: Cannot read property 'options' of undefined

### ISSUE THREAD

**Issue by petermikitsh** [feathersjs/feathers-authentication-client#26]
### Steps to reproduce

When loading my webpage, I occasionally get the stacktrace below, thrown here in [passport.js](https://github.com/feathersjs/feathers-authentication-client/blob/master/src/passport.js#L63):

```
Uncaught TypeError: Cannot read property 'options' of undefined
    at Socket.<anonymous> (passport.js:89)
    at Socket.Emitter.emit (index.js:133)
    at socket.js:321
    at pause (polling.js:81)
    at XHR.<anonymous> (polling.js:92)
    at XHR.on (index.js:65)
    at XHR.Emitter.emit (index.js:133)
    at XHR.Polling.onData (polling.js:154)
    at Request.<anonymous> (polling-xhr.js:126)
    at Request.Emitter.emit (index.js:133)
```

### Expected behavior

This error should never be thrown.

### Actual behavior

It gets thrown, only once-in-awhile in a hard-to-reproduce kind of way.

### System configuration

**Module versions** (especially the part that's not working):
**feathers-authentication-client**: 0.1.7
**NodeJS version**: 6.0.0
**Operating System**: Mac OS X
**Browser Version**: Chrome Latest
**React Native Version**: N/A
**Module Loader**: webpack

**Comment by petermikitsh** [comment]
I'm seeing this error more frequently in Firefox.

<img width="685" alt="screen shot 2017-02-04 at 7 37 25 pm" src="https://cloud.githubusercontent.com/assets/1571918/22623488/662770e0-eb11-11e6-8432-f69426c33990.png">

<img width="533" alt="screen shot 2017-02-04 at 7 37 33 pm" src="https://cloud.githubusercontent.com/assets/1571918/22623490/6a14c3c4-eb11-11e6-9f7c-492da336d156.png">

**Comment by daffl** [comment]
I think this is a valid error because the `this` in that context is definitely wrong. I bet it only happens intermittently because sometimes upgrade happens before being authenticated.

**Comment by daffl** [comment]
I have a fix in https://github.com/feathersjs/feathers-authentication-client/pull/27. Any chance you can give it a try?

**Comment by petermikitsh** [comment]
@daffl I have tried it out. Looks good, no more exceptions! Thanks for the quick fix.
