### ISSUE TITLE
exp claim should be optional

### ISSUE THREAD

**Issue by whollacsek** [feathersjs/feathers-authentication-client#33]
### Steps to reproduce

- server returns a valid jwt without `exp` claim, which is stored in localstorage
- client calls `app.authenticate()` but get an error about jwt not found

### Expected behavior
jwt without `exp` claim should pass `payloadIsValid` check.

### Actual behavior
On client-side `app.authenticate()` does not work if the jwt does not have `exp` claim set. The `exp` claim should be optional. The function responsible for this check is: https://github.com/feathersjs/feathers-authentication-client/blob/master/src/utils.js#L22

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
feathers-authentication-client: 0.2.0

**NodeJS version**:
6.9.2

**Operating System**:
Ubuntu

**Comment by marshallswain** [comment]
@whollacsek  I've never had a use for not having an `exp` claim.  Would this mean the token never expires?  https://tools.ietf.org/html/rfc7519#section-4.1.4

**Comment by whollacsek** [comment]
@marshallswain yes for some use cases like in a mobile app

**Comment by daffl** [comment]
I'm not sure tokens that never expire are a good idea. I think the fix in your PR makes sense though.

**Comment by whollacsek** [comment]
yeah I know it's a heated debate around how jwt should be used, but since no consensus was made on token refresh strategy and token protection, I feel it's better to not try and implement something that's wrong. Having a bad implementation of token refresh is worse then having a never expiring token.

**Comment by marshallswain** [comment]
Ok.  This makes sense as long as you have to explicitly turn off the `exp` property, which I'm pretty sure is the case right now.  Please correct me if I'm wrong.  I'm just concerned that it will be too easy to enable non-expiring tokens for those who don't fully understand the implications of using them.

**Comment by whollacsek** [comment]
yes I had to explicitly do
```js
  const options = hook.app.get('auth')
  delete options.jwt.exp // <= explicit delete
  app.passport.createJWT({userId}, options, ...)
```
