### ISSUE TITLE
Proper way to save jwt in cookies

### ISSUE THREAD

**Issue by tention** [feathersjs/feathers-authentication-client#41]
Am very new to this client. Sorry but this might not be an issue to the library, I could not get jwt properly stored within cookie after login. Cookie is enabled in the properties. Did I miss out any other configuration?

`    "cookie": {
      "enabled": true,
      "name": "feathers-jwt",
      "httpOnly": false,
      "secure": false
    }
`

Should the storage be changed to something else for cookies to work?

`export const app = feathers()
  .configure(rest(host).superagent(superagent))
  .configure(feathers.hooks())
  .configure(auth({ 
    storage: window.localStorage,
    type: 'jwt',
  }));
`

Thanks

**Comment by marshallswain** [comment]
Those options should be configured on the server.  That's all it should take.

**Comment by tention** [comment]
Should I add a hook to include setCookie on the server? or it should be there automatically? 

Cookies was added successfully when i used oauth2 (facebook), but not the local.

**Comment by marshallswain** [comment]
Hmmm...  If that's the case, please open an issue in `feathers-authentication-local` and close this one.

**Comment by tention** [comment]
feathersjs/feathers-authentication-local#17
