### ISSUE TITLE
Relation with feathers-authentication

### ISSUE THREAD

**Issue by whollacsek** [feathersjs/feathers-authentication-client#6]
Sorry for not following the contribution guidelines but this issue is a question.

This project seems to be a new one, I'm wondering what is the relation of this module with the already existing https://github.com/feathersjs/feathers-authentication ?

**Comment by marshallswain** [comment]
Not a problem.  There used to be a `client` folder in the `feathers-authentication` repo.  It has been moved instead to this repo.  It's undergoing a refactor before we publish it as a separate module, though.  So, for now, you can just continue to access the client authentication plugin like this:
```js
import authentication from 'feathers-authentication/client';
```

Once this module is complete and published, you'll do
```js
import authentication from 'feathers-authentication-client';
```

**Comment by whollacsek** [comment]
OK I see, thanks!
